[MENTORING-T-112] Kotlin 2주차
BI-kotlin-in-action-2ND/SeungGyunPark pull request #1
Opened 2024-01-23 14:52 UTC by seungyun-Park

3문제 풀었습니다
- 1032
- 1057
- 1748
코틀린 문법이 적응하기 어려워서 이번 주는 좀 쉬운 난이도의 문제로 골랐습니다..
깃허브도 처음 사용해보아서 많이 헤맸는데 혹시 깃에 뭔가 잘못된게 있다면 말씀해주시면 고치겠습니다..!

2024-01-23 15:00 UTC, konempty requested changes
굿굿 역시 초반엔 요렇게 간단한 문제를 풀어보는게 좋다고 생각합니다~!
리뷰드린게 많지는 않지만 리뷰 반영후 저한테 재리뷰 요청 주세요!

2024-01-23 15:00 UTC, konempty commented on src/1032.kt
> +}
<img width="260" alt="스크린샷 2024-01-23 오후 11 59 11" src="https://github.com/BI-kotlin-in-action-2ND/SeungGyunPark/assets/44064530/8532ca5c-db20-4887-834d-7276e5e12c0c">

오호 파일끝 개행이 빠져있네요 ㅋㅋㅋ..
파일끝 개행이 표준 규칙 이기도 하고 일부시스템에서는 에러의 원인이 되기도 한답니다 ㅋㅋㅋ
https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
요 블로그 참고해서 IDE에 파일끝 개행 설정 넣어주세요~!

2024-01-23 15:00 UTC, konempty commented on src/1032.kt
> +    val names = List(n) { readln() }
크기가 변하지 않는다면 List보다는 Array가 나을것 같습니다~!
```kotlin
val names = Array(){ readln() }
```

2024-01-23 15:00 UTC, konempty commented on src/1032.kt
> +    val result = StringBuilder()
ㅋㅋㅋㅋ 요거 아마 성능때문에 그냥 스트링이 아닌 스트링 빌더를 쓰시는것 같은데
자바 6,7 까진 잘하신 코드인데
JDK 8인가 9부터는 동적 바인딩을 통해 String +연산도 자동으로 StringBuilder를 통한 연산으로 치환됩니다~!

https://howtodoinjava.com/java/string/string-concatenation-performance/#2-compiler-optimization-for-string-concatenation
바이트 코드까지 분석하는 블로그라 이해에 도움이 될것 같아요!

2024-01-23 15:00 UTC, konempty commented on src/1057.kt
> +    val (n, jimin, hansu) = readln().split(" ").map { it.toInt() }
👍 👍

2024-01-24 07:48 UTC, seungyun-Park reviewed
수정했습니다!

2024-01-24 08:27 UTC, konempty approved these changes
크 첫과제 수고하셨습니다 👍 👍 
모든 파일의 파일끝 개행 수정하신뒤 머지하셔도 좋을것 같습니다!
그리고 다른 분들은 어떤 리뷰를 받았는지 보시고 숙지해두시면
앞으로 리뷰받으실때 도움이 될것 같습니다~!

2024-01-24 08:27 UTC, konempty commented on src/1057.kt
> +}
<img width="303" alt="스크린샷 2024-01-24 오후 5 24 53" src="https://github.com/BI-kotlin-in-action-2ND/SeungGyunPark/assets/44064530/ef45acfd-e590-414c-98c5-c97f27f2918f">
ㅋㅋㅋ... 파일끝 개행 전부 챙겨주세요

2024-01-24 13:27 UTC, merged