코틀린 3주차
BI-kotlin-in-action-2ND/SeungGyunPark pull request #2
Opened 2024-01-30 14:52 UTC by seungyun-Park

두문제 풀었습니다
- 1004
- 19637

2024-01-30 15:16 UTC, konempty requested changes
크 고생하셨습니다 👍 👍 
리뷰 확인후 조금만 수정 부탁드립니다~!

2024-01-30 15:16 UTC, konempty commented on src/1004.kt
> +import kotlin.math.*
오노 ㅠㅠㅠ
와일드 카드 임포트는 지양해야합니다 ㅠㅠㅠ
IDE 설정에서 와일드 임포트가 되지 않도록 설정 부탁드립니다

https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij

2024-01-30 15:16 UTC, konempty commented on src/1004.kt
> +    var result : Array<Int> = arrayOf()
제가 수업때 말씀드렸는데
Array\<Int>를 쓸바에야 IntArray를 쓰는게 이득입니다~!

또한 여기에서 var로 하신 이유는
엘리먼트의 개수가 변해야하는데 Array는 크기 불변 컬렉션이라 그러신것 같네요 ㅋㅋㅋ..
따라서 결과적으로는 MutableList<Int>를 쓰는게 맞아요

2024-01-30 15:16 UTC, konempty commented on src/19637.kt
> +): String{
바이너리 서치를 직접 구현하기보다
저번 수업시간에 알려드린 
kotlin에서 지원하는 binarySearch를 활용하는게 좀더 코틀린 스러운 코드가 될것 같아요!

2024-01-30 15:16 UTC, konempty commented on src/1004.kt
> +            }
으흠 여기는 XOR 연산이면 한줄로 줄일수 있을것 같은데
```kotlin
if((cr > dis1) xor (cr > dis2)){
    count++
}
```
요렇게요!

2024-01-30 15:16 UTC, konempty commented on src/1004.kt
> +        println(result[it])
result에 저장했다가 한번에 출력하는 이유가 궁금합니다!

        result += count
요 코드 대신에
println(count)
라고 했어도 되는거 아니었을까요??

2024-01-31 08:55 UTC, seungyun-Park commented on src/1004.kt
> +        println(result[it])
결과값이 각 테스트 케이스의 입력이 끝나면 바로 나와서, 모든 케이스의 입력이 끝난 후 마지막에 한번에 나오도록 하려고 그랬습니다..!

2024-01-31 09:35 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
리뷰는 아니고 궁금한게 있어서 코멘트 달았는데 답변 부탁드리구요
이제 머지하셔도 좋습니다~!

2024-01-31 09:35 UTC, konempty commented on src/1004.kt
> +        println(result[it])
아하 그런 의도라면 좋습니다~!

2024-01-31 09:35 UTC, konempty commented on src/19637.kt
> +        val index = style.indexOfFirst { it.second >= power }
어.. 아마 요건 바이너리 서치처럼 O(n log n)이 아니라 O(n)의 탐색일거예요
바이너리 서치를 사용을 포기하신 이유가 있을까요??

2024-01-31 13:36 UTC, seungyun-Park commented on src/19637.kt
> +        val index = style.indexOfFirst { it.second >= power }
이 문제에서는 탐색에 실패해도 result값을 가져와서 그때의 칭호를 출력해야 하는데, 코틀린이 제공하는 binarySearch는 탐색에 실패했을때 음수값을 가져와버려서 다른 방법을 찾다가 저렇게 썼습니다..

2024-01-31 13:37 UTC, merged

2024-01-31 13:53 UTC, konempty commented on src/19637.kt
> +        val index = style.indexOfFirst { it.second >= power }
으흠 binarySearch의 문서를 제대로 읽어 봤다면 아셨을 텐데
그냥 음수가 아니라 min인덱스를 음수를 취해서 반환하기 때문에
```kotlin
var index = style.binarySearch(doSomething())
if(index < 0) index = -index

// 그 다음 로직
```
요렇게 하면 효율적이면서 같은 동작을 하는 코드를 짤수 있었을 거예요

2024-01-31 14:33 UTC, seungyun-Park commented on src/19637.kt
> +        val index = style.indexOfFirst { it.second >= power }
헉 그렇군요 참고하겠습니다 감사합니다 !!!